### ISSUE TITLE
Build the solution

### ISSUE THREAD

**Issue by zranwang** [stereolabs/zed-unreal-examples#4]
Hello, Think you for your repositories. Build the solution by pressing Ctrl + F5, but I meet some errors. as following:
1. Unable to instantiate module 'Stereolabs': ZED SDK Minor Version mismatch: found 5 expected 7
2. E:\3Dtelepresence\unrealengine\Unreal_ZED\zed-unreal-examples-master\UE4_Examples\ZEDSamples.uproject" -WaitMutex -FromMsBuild”  Please verify that you have sufficient permissions to run this command.

I don't deal with this error, please give me some suggestions. I Build the Engine according to https://www.stereolabs.com/docs/unreal/, before starting to build the solution

**Comment by obraun-sl** [comment]
Hi,

Please use the ZED SDK 2.7 (or 2.8 if using the custom engine for 2.8). 
You can download the 2.7 here : 
https://www.stereolabs.com/developers/release/2.7/

Best,
OB

**Comment by zranwang** [comment]
Hi, Thank you for your response. I only find the custom engine for the zed sdk 2.5 in https://github.com/Stereolabs-Unreal/UnrealEngine. please tell me how to do get the custom engine for zed sdk 2.7. Because I find the zed-unreal-plugin updated by you for zed sdk 2.7 and cuda10.0 in https://github.com/stereolabs/zed-unreal-plugin

**Comment by zranwang** [comment]
I find the zed-unreal-plugin updated by you for zed sdk 2.5 and cuda9.0 in  https://github.com/stereolabs/zed-unreal-plugin/releases/tag/v2.5.x, and the problem was resolved.
