### ISSUE TITLE
Unreal Sample Projects Only Shows Black

### ISSUE THREAD

**Issue by calonpintar** [stereolabs/zed-unreal-examples#7]
Hello, finally done compiling custom Unreal Engine 4.21 in 3 days after many unsuccessful try.
Downloaded Zed Unreal plugin for SDK 3.1, and extracted to Plugin folder inside the Zed Unreal Sample Folder, all runs smoothly, no errors, but when I hit play button, searching camera, looks normal, but in the end, it only shows black. What I'm missing?

**Comment by obraun-sl** [comment]
It seems to be an issue with 3.1 and the 3.1 branch of the plugin. 
Can you try with SDK 3.0 and ue4.21_sdk3.0 branch ?
In the meantime, we are fixing it for 3.1

**Comment by calonpintar** [comment]
Hi, thanks for your reply. I can confirm now it is working normally using SDK 3.0 and ue4.21_sdk3.0 branch. Thank you!
Can't wait developing with SDK 3.2 in Unreal.
Cheers.

**Comment by GR90** [comment]
you should set the leftfinalplane location to (1000,0,0).  now i have a new problem : when i closed this project, a fate error window appear.  sdk3.0 and sdk3.1 is the same problem

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x00000010

0x00007ffc31e38b2b UE4Editor-Core.dll!__TBB_LockByte() []
0x00007ffc31e39573 UE4Editor-Core.dll!rml::internal::Block::freePublicObject() []
0x00007ffc31e3a0b2 UE4Editor-Core.dll!rml::internal::ExtMemoryPool::initTLS() []
0x00007ffc31a74507 UE4Editor-Core.dll!FMemory::Free() [d:\unrealengine-4.21-zed\engine\source\runtime\core\public\hal\fmemory.inl:76]
0x00007ffbfb4dabc6 UE4Editor-Stereolabs.dll!sl::SensorsData::~SensorsData() []
0x00007ffbfb4dac1e UE4Editor-Stereolabs.dll!USlCameraProxy::~USlCameraProxy() []
0x00007ffbfb4dfa73 UE4Editor-Stereolabs.dll!USlCameraProxy::`vector deleting destructor'() []
0x00007ffc2df6ccf1 UE4Editor-CoreUObject.dll!IncrementalPurgeGarbage() [d:\unrealengine-4.21-zed\engine\source\runtime\coreuobject\private\uobject\garbagecollection.cpp:1311]
0x00007ffc2e028a26 UE4Editor-CoreUObject.dll!StaticExit() [d:\unrealengine-4.21-zed\engine\source\runtime\coreuobject\private\uobject\obj.cpp:4316]
0x00007ffc2de2c007 UE4Editor-CoreUObject.dll!TBaseStaticDelegateInstance<void __cdecl(void)>::ExecuteIfSafe() [d:\unrealengine-4.21-zed\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:813]
0x00007ff788f2fe04 UE4Editor.exe!TBaseMulticastDelegate<void>::Broadcast() [d:\unrealengine-4.21-zed\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:974]
0x00007ff788f2fa96 UE4Editor.exe!FEngineLoop::AppPreExit() [d:\unrealengine-4.21-zed\engine\source\runtime\launch\private\launchengineloop.cpp:4411]
0x00007ff788f342bf UE4Editor.exe!FEngineLoop::Exit() [d:\unrealengine-4.21-zed\engine\source\runtime\launch\private\launchengineloop.cpp:3189]
0x00007ff788f34d85 UE4Editor.exe!GuardedMain() [d:\unrealengine-4.21-zed\engine\source\runtime\launch\private\launch.cpp:185]
0x00007ff788f34dca UE4Editor.exe!GuardedMainWrapper() [d:\unrealengine-4.21-zed\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
0x00007ff788f43b4a UE4Editor.exe!WinMain() [d:\unrealengine-4.21-zed\engine
