### ISSUE TITLE
ZED SDK missing

### ISSUE THREAD

**Issue by lt613** [stereolabs/zed-unreal-examples#9]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

download the ZED_unreal_plugin zip from gitup, I want to use it successfully it did not work

### Steps to Reproduce

1.follow the step from git and zed documantation
2.
3.
...

### Expected Result

run successfully

### Actual Result

![image](https://user-images.githubusercontent.com/92131840/165006510-d1ca746d-b20e-417f-8b0c-63d9d7099221.png)

### ZED Camera model

ZED 2i

### Environment

```shell
ZED SDK version:3.7
vs version:2022
ue version:4.27
```

### Anything else?

no

**Comment by obraun-sl** [comment]
Hi,
You need to use the custom Unreal Engine to be able to use the stereolabs unreal plugin.
https://www.stereolabs.com/docs/unreal/#stereolabs-custom-engine-for-armr

(You also need the ZED SDK installed)
